name: Programming Logic First Task
on:
  pull_request:
    branches: [first-task]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Clone tests repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
         owner: 'Telos-Conecta'
         repository: 'tests-simulator-programming-logic-kotlin'
         access-token: ${{ secrets.ACCESS_TOKEN }}
           
      # Move test path
      - name: Move test path to the root
        run: mv tests-simulator-programming-logic-kotlin/first-task src/test/kotlin 

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew test
